{% set name = "opentelemetry-exporter-gcp-trace" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8b2572235b4683563c21caa8bc97071df11f766f477274a5547751d74eae0643

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-cloud-trace ~=1.1
    - opentelemetry-api ~=1.30
    - opentelemetry-sdk ~=1.30
    - opentelemetry-resourcedetector-gcp ==1.*,>=1.5.0dev0
    # - typing_extensions 

test:
  imports:
    - opentelemetry
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/tree/main/opentelemetry-exporter-gcp-trace
  summary: Google Cloud Trace exporter for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
